# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0.xci
# IP: The module: 'system_spi_shared_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0.xci
# IP: The module: 'system_spi_shared_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_spi_shared_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
