# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
# IP: The module: 'system_tier2_xbar_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_tier2_xbar_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
# IP: The module: 'system_tier2_xbar_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Pynq/Pynq_v2.1_SPOT/boards/Pynq-Z1/base/base/base.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_tier2_xbar_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
